// src/modules/__context__/features/__feature__/__feature__.controller.ts
// Generated by: pnpm exec nest g co modules/__context__/features/__feature__ --no-spec
// Then reshaped like this: resource route prefix, one `handle` method, Result → HTTP.
import { Body, Controller, HttpCode, Post } from '@nestjs/common';
import { ZodSerializerDto } from 'nestjs-zod';
import { unwrapOrThrowHttp } from '../../../../shared/http/result-to-http.js';
import { __contextCamel__HttpErrors } from '../../__context__.http-errors.js';
import { __Feature__Dto, __Feature__ResponseDto } from './__feature__.dto.js';
import { __Feature__UseCase } from './__feature__.use-case.js';

@Controller('__context__')
export class __Feature__Controller {
  constructor(private readonly useCase: __Feature__UseCase) {}

  @Post()
  @HttpCode(201)
  @ZodSerializerDto(__Feature__ResponseDto)
  async handle(@Body() body: __Feature__Dto): Promise<__Feature__ResponseDto> {
    return unwrapOrThrowHttp(await this.useCase.execute(body), __contextCamel__HttpErrors);
  }
}

// Non-HTTP entry points keep the same shape:
// - BullMQ: @Processor('queue') class with process(job) { const r = await useCase.execute(job.data); if (r.isErr()) throw ... }
// - Events: @OnEvent('__entity__.created') handle(event) { return this.useCase.execute(...) }
// - Cron:   @Cron('0 * * * *') handle() { ... }
